name: tarefinha
services:
    caddy:
        image: caddy:2.8-alpine
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/Caddyfile:/etc/caddy/Caddyfile
            - caddy_config:/config
            - caddy_data:/data
    composer:
        image: composer/composer:2.7.9
        restart: no
        command: install
        volumes:
            - .:/app

    php:
        build:
            dockerfile: ./docker/php.Dockerfile
        restart: unless-stopped
        volumes:
            - .:/var/www/html

    postgres:
        image: postgres:15-alpine
        restart: unless-stopped
        environment:
            POSTGRES_DB: tarefinha
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - pgsql:/var/lib/postgresql/data

    redis:
        image: redis:alpine


volumes:
    pgsql:
    caddy_data:
    caddy_config:
